export default `
async function load(file){if(!file||!file.type.startsWith('image/'))return toast('이미지 파일만 가능해');pause();if(file.type==='image/gif'||/\.gif$/i.test(file.name||'')){toast('GIF 프레임 분석 중...');try{let fr=await decodeGifFrames(file,{maxFrames:MAX});setFrames(fr.map(f=>f.canvas),file.name||'animation.gif','gif',fr.map(f=>f.delay));tab('sheet');return}catch(e){console.error(e);toast('GIF를 프레임으로 나누지 못했어. 일반 이미지로 시도할게')}}if(S.url)URL.revokeObjectURL(S.url);S.frames=null;let url=URL.createObjectURL(file),img=new Image();img.onload=()=>{Object.assign(S,{img,url,name:file.name||'Pasted Image',w:img.naturalWidth,h:img.naturalHeight,source:'sheet',frame:0,dir:1,cellSize:snap128(S.cellSize||128)});setLoaded(true);syncFilters();try{let b=smartDetect(S.img);S.cols=b.cols;S.rows=b.rows}catch(e){}sync();draw();film();updateSheet(true);play();toast('이미지 로드 완료 · '+S.cols+' × '+S.rows+' · cell '+S.cellSize+'px')};img.onerror=()=>toast('이미지를 읽지 못했어');img.src=url}
function save(){if(ready())saveCanvasPNG(previewCanvas(S.frame,true),'sprite-frame-'+String(S.frame+1).padStart(3,'0')+'.png')}
async function zip(){if(!ready())return;let n=count(),was=S.playing;pause();try{await saveFramesZip({frameCount:n,filename:name()+'-frames.zip',prefix:'frame',renderFrame:i=>previewCanvas(i,true),onProgress:(i,t)=>{if(i===t||i%5===0)toast('ZIP 생성 중 '+i+'/'+t)}});toast('ZIP 저장 완료 · '+n+'프레임')}catch(e){console.error(e);toast('ZIP 저장 중 오류가 났어')}if(was)play()}
function saveSheet(){if(!ready())return;saveCanvasPNG(sheetCanvas(),name()+'-sheet-'+S.cols+'x'+S.rows+'-'+S.cellSize+'px.png');updateSheet(true);toast('스프라이트 시트 저장 · '+S.cols+' × '+S.rows+' · cell '+S.cellSize+'px')}
function sheet(){S.cols=cl(E.cols.value,1,12);S.rows=cl(E.rows.value,1,12);S.cellSize=snap128(E.cellSize?E.cellSize.value:S.cellSize);S.sheetGuides=E.sheetGuides?E.sheetGuides.checked:S.sheetGuides;S.frame=Math.min(S.frame,count()-1);sync();draw();updateSheet(false)}
function trans(){S.ox=cl(E.ox.value,-128,128);S.oy=cl(E.oy.value,-128,128);S.tilt=cl(E.tilt.value,-180,180);S.focusX=cl(E.focusX.value,-512,512);S.focusY=cl(E.focusY.value,-512,512);sync();draw();updateSheet(false)}
function playback(){S.interval=cl(E.interval.value,10,100);S.curve=E.curve.value;S.curveVal=cl(E.curveVal.value,0,100);S.mode=E.mode.value;sync();info();if(S.playing)play()}
function fills(){document.querySelectorAll('.scrub').forEach(z=>{let i=$(z.dataset.target);if(!i)return;let mn=+(z.dataset.min||i.min||0),mx=+(z.dataset.max||i.max||100),v=cl(i.value,mn,mx),f=z.querySelector('.fill');if(f)f.style.width=Math.max(0,Math.min(100,(v-mn)/(mx-mn)*100))+'%'})}
`;
