export default `
const $=id=>document.getElementById(id),ids='card stage empty preview canvas film status frameTxt pick clip undo redo reset file play stop prev next first interval curve curveVal mode cols rows count auto delFrame sheetSave sheetPreview sheetPreviewCanvas sheetChannel sheetInfo ox oy tilt focusX focusY focusReset scale scaleTxt bg save zip qAuto qPlay qSave qZip qPreset iFile iSheet iFrame iCount iFps iCurve iOffset iTilt toast fEnable fBypass fBright fBrightTxt fContrast fContrastTxt fSat fSatTxt fHue fHueTxt fCel fCelSteps fCelStepsTxt fPixel fPixelSize fPixelSizeTxt fOutline fOutlineWidth fOutlineColor fAlpha fAlphaTh fAlphaThTxt fAlphaValue fAlphaValueTxt fAlphaGen fAlphaMode fAlphaSmooth fAlphaSmoothRadius fAlphaSmoothRadiusTxt fDrop fDropColor fDropPick fDropTol fDropTolTxt fDropSoft fDropSoftTxt fRamp fRampPreset fRampMix fRampMixTxt fRampColor0 fRampColor1 fRampColor2 fRampColor3 rampSwatches fReset fPreset'.split(' '),E={};ids.forEach(id=>E[id]=$(id));
const base=document.createElement('canvas'),bctx=base.getContext('2d',{willReadFrequently:true}),MAX=144,store='spritePastePlayer.filterState.v6';
const S={img:null,url:'',name:'',source:'sheet',frames:null,fw:0,fh:0,w:0,h:0,cols:3,rows:3,frame:0,interval:83,curve:'linear',curveVal:50,mode:'loop',dir:1,timer:null,playing:false,scale:3,ox:0,oy:0,tilt:0,focusX:0,focusY:0,preset:0,filters:loadFilters()};
function loadFilters(){try{return Object.assign(defaultFilters(),JSON.parse(localStorage.getItem(store)||'{}'))}catch(e){return defaultFilters()}}
function saveFilters(){try{localStorage.setItem(store,JSON.stringify(S.filters))}catch(e){}}
const hasFrames=()=>S.frames&&S.frames.length,ready=()=>hasFrames()||S.img,cells=()=>Math.max(1,S.cols*S.rows),count=()=>hasFrames()?S.frames.length:cells(),fs=()=>hasFrames()?{w:S.fw,h:S.fh}:S.img?{w:S.w/S.cols,h:S.h/S.rows}:{w:1,h:1},cl=(v,a,b)=>Math.max(a,Math.min(b,Math.round(Number(v)||0))),hex=v=>/^#[0-9a-f]{6}$/i.test(v||''),name=()=>String(S.name||'sprite').replace(/\.[^.]+$/,'')||'sprite';
function activeFilter(f){return!!(f.cel||f.ramp||f.pixel||f.outline||f.alphaCut||f.alphaGen||f.alphaSmooth||f.colorKey||(f.alphaValue!=null&&f.alphaValue!==100)||f.brightness||f.contrast||f.saturation||f.hue)}
function cleanColors(a){let b=RAMPS.fire;return[0,1,2,3].map(i=>hex(a?.[i])?a[i]:b[i])}
function toast(t){E.toast.textContent=t;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),1600)}
`;