export default `
function sheetCanvas(){let size=snap128(S.cellSize),out=document.createElement('canvas'),x=out.getContext('2d');out.width=size*S.cols;out.height=size*S.rows;x.imageSmoothingEnabled=false;x.clearRect(0,0,out.width,out.height);frameList(count(),cells()).forEach((src,slot)=>{let c=cellCanvas(src,true),fit=Math.min(size/c.width,size/c.height),dw=Math.max(1,Math.round(c.width*fit)),dh=Math.max(1,Math.round(c.height*fit)),dx=(slot%S.cols)*size+Math.round((size-dw)/2),dy=Math.floor(slot/S.cols)*size+Math.round((size-dh)/2);x.drawImage(c,dx,dy,dw,dh)});return out}
function chan(src,m){if(m==='rgba')return src;let o=document.createElement('canvas'),x=o.getContext('2d',{willReadFrequently:true});o.width=src.width;o.height=src.height;x.drawImage(src,0,0);let im=x.getImageData(0,0,o.width,o.height),d=im.data;for(let i=0;i<d.length;i+=4){let v=m==='r'?d[i]:m==='g'?d[i+1]:m==='b'?d[i+2]:d[i+3];d[i]=d[i+1]=d[i+2]=v;d[i+3]=255}x.putImageData(im,0,0);return o}
function drawSheetGuides(ctx,w,h){let size=snap128(S.cellSize),lw=Math.max(1,Math.round(size/128));ctx.save();ctx.lineWidth=lw;ctx.strokeStyle='rgba(255,255,255,.85)';ctx.strokeRect(.5,.5,w-1,h-1);ctx.beginPath();for(let x=size;x<w;x+=size){ctx.moveTo(x+.5,0);ctx.lineTo(x+.5,h)}for(let y=size;y<h;y+=size){ctx.moveTo(0,y+.5);ctx.lineTo(w,y+.5)}ctx.strokeStyle='rgba(120,168,255,.82)';ctx.stroke();ctx.setLineDash([Math.max(4,size/24),Math.max(3,size/32)]);ctx.beginPath();for(let c=0;c<S.cols;c++){let cx=c*size+size/2;ctx.moveTo(cx+.5,0);ctx.lineTo(cx+.5,h)}for(let r=0;r<S.rows;r++){let cy=r*size+size/2;ctx.moveTo(0,cy+.5);ctx.lineTo(w,cy+.5)}ctx.strokeStyle='rgba(255,255,255,.5)';ctx.stroke();ctx.setLineDash([]);ctx.lineWidth=lw+1;ctx.beginPath();ctx.moveTo(w/2+.5,0);ctx.lineTo(w/2+.5,h);ctx.moveTo(0,h/2+.5);ctx.lineTo(w,h/2+.5);ctx.strokeStyle='rgba(255,209,102,.95)';ctx.stroke();ctx.restore()}
function updateSheet(force=false){if(!ready()||!E.sheetPreviewCanvas)return;if(!force&&E.sheetPreviewCanvas.width===0)return;S.cellSize=snap128(S.cellSize);let raw=sheetCanvas(),mode=E.sheetChannel.value,view=chan(raw,mode),x=E.sheetPreviewCanvas.getContext('2d');E.sheetPreviewCanvas.width=view.width;E.sheetPreviewCanvas.height=view.height;x.clearRect(0,0,view.width,view.height);x.drawImage(view,0,0);if(S.sheetGuides)drawSheetGuides(x,view.width,view.height);let total=count(),slot=cells(),picked=frameList(total,slot).length,range=hasFrames()?activeRange():[0,total-1],sample=hasFrames()?('활성 '+(range[0]+1)+'~'+(range[1]+1)+' / '+total+'프레임 → '+picked+'셀'):(picked+'/'+slot+'셀');E.sheetInfo.textContent=S.cols+' × '+S.rows+' · cell '+S.cellSize+'px · '+view.width+' × '+view.height+'px · '+sample+' · '+mode.toUpperCase()}
function play(){if(!ready())return;pause(false);S.playing=true;E.play.textContent='재생 중';E.qPlay.textContent='정지';tick()}
function pause(btn=true){clearTimeout(S.timer);S.timer=null;S.playing=false;if(btn){E.play.textContent='재생';E.qPlay.textContent='재생'}}
function tick(){if(!S.playing)return;S.timer=setTimeout(()=>{let c=count();if(S.mode==='pingpong'){let n=S.frame+S.dir;if(n>=c){S.dir=-1;S.frame=Math.max(0,c-2)}else if(n<0){S.dir=1;S.frame=Math.min(1,c-1)}else S.frame=n}else if(S.mode==='once'){if(S.frame>=c-1)return pause();else S.frame++}else S.frame=(S.frame+1)%c;draw();tick()},delay())}
function delay(){let b=cl(S.interval,10,100),c=count(),t=c<=1?0:S.frame/(c-1),a=cl(S.curveVal,0,100)/100,m=1;if(S.curve==='easeIn')m=1.7-1.2*t;else if(S.curve==='easeOut')m=.5+1.2*t;else if(S.curve==='easeInOut')m=.55+1.45*Math.abs(2*t-1);else if(S.curve==='burst')m=t<.32?1.75:t<.72?.48:1.15;return Math.round(Math.max(4,Math.min(220,b*((1-a)+a*m))))}
function bestGrid(n){let c=Math.ceil(Math.sqrt(n)),r=Math.ceil(n/c);if(c>12){c=12;r=Math.ceil(n/12)}if(r>12){r=12;c=Math.ceil(n/12)}return{cols:cl(c,1,12),rows:cl(r,1,12)}}
`;
