import{applyFilters,defaultFilters,FILTER_PRESETS,RAMPS}from'./filters.js';
import{smartDetect}from'./smart-detect.js';
import{saveCanvasPNG,saveFramesZip}from'./export.js';
import{decodeGifFrames}from'./gif-decoder.js';
import p1 from './app-chunk-1.js';
import p2 from './app-chunk-2.js';
import p3 from './app-chunk-3.js';
import p4 from './app-chunk-4.js';
import p5 from './app-chunk-5.js';
import p6 from './app-chunk-6.js';
import p7 from './app-chunk-7.js';
import p8 from './app-chunk-8.js';
import p9 from './app-chunk-9.js';
import p10 from './app-chunk-10.js';
new Function('applyFilters','defaultFilters','FILTER_PRESETS','RAMPS','smartDetect','saveCanvasPNG','saveFramesZip','decodeGifFrames',p1+p2+p3+p4+p5+p6+p7+p8+p9+p10)(applyFilters,defaultFilters,FILTER_PRESETS,RAMPS,smartDetect,saveCanvasPNG,saveFramesZip,decodeGifFrames);
