import {applyFilters,defaultFilters,FILTER_PRESETS,RAMPS} from './filters.js';
import {smartDetect} from './smart-detect.js';
import {saveCanvasPNG,saveFramesZip} from './export.js';
const $=id=>document.getElementById(id);
const ids=['card','stage','empty','preview','canvas','film','status','frameTxt','pick','clip','undo','redo','reset','file','play','stop','prev','next','first','interval','curve','curveVal','mode','cols','rows','count','auto','ox','oy','tilt','scale','scaleTxt','bg','save','zip','qAuto','qPlay','qSave','qZip','qPreset','iFile','iSheet','iFrame','iCount','iFps','iCurve','iOffset','iTilt','toast','fEnable','fBypass','fPixel','fPixelSize','fPoster','fPosterSteps','fRamp','fRampPreset','fRampColor0','fRampColor1','fRampColor2','fRampColor3','rampSwatches','fDither','fDitherAmount','fNoise','fNoiseAmount','fOutline','fOutlineWidth','fBloom','fBloomAmount','fChrom','fChromAmount','fGlitch','fGlitchAmount','fFxSketch','fFxSketchPreset','fFxSketchStrength','fFxSketchSteps','fFxSketchContrast','fFxSketchEdge','fFxSketchClean','fReset','fPreset'];
const E={};ids.forEach(id=>E[id]=$(id));
const BASE=document.createElement('canvas'),baseCtx=BASE.getContext('2d',{willReadFrequently:true});
const S={img:null,url:'',name:'',w:0,h:0,cols:3,rows:3,interval:83,curve:'linear',curveVal:50,scale:3,ox:0,oy:0,tilt:0,frame:0,dir:1,playing:false,timer:null,mode:'loop',hist:[],redo:[],ready:false,filters:null,presetIndex:0};
const STORE_KEY='spritePastePlayer.filterState.v3',TAB_KEY='spritePastePlayer.activeTab.v1';
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const clamp=(v,min,max)=>{const n=num(v);return Math.max(min,Math.min(max,n===null?min:n))};
const clone=o=>JSON.parse(JSON.stringify(o));
const count=()=>Math.max(1,S.cols*S.rows);
const fs=()=>S.img?{w:S.w/S.cols,h:S.h/S.rows}:{w:0,h:0};
const r2=v=>Math.round(v*100)/100;
const isHex=v=>/^#[0-9a-f]{6}$/i.test(v||'');
function cleanColors(colors){const base=RAMPS.fire;return [0,1,2,3].map(i=>isHex(colors?.[i])?colors[i]:base[i])}
function hasActiveFilters(f){return !!(f.pixel||f.poster||f.ramp||f.dither||f.noise||f.outline||f.bloom||f.chrom||f.glitch||f.fxSketch)}
function currentRampPalette(){return S.filters.rampPreset==='custom'?cleanColors(S.filters.rampColors):(RAMPS[S.filters.rampPreset]||RAMPS.fire)}
function loadStoredFilters(){try{const raw=localStorage.getItem(STORE_KEY);if(!raw)return defaultFilters();return Object.assign(defaultFilters(),JSON.parse(raw))}catch(e){return defaultFilters()}}
function saveStoredFilters(){try{localStorage.setItem(STORE_KEY,JSON.stringify(S.filters))}catch(e){}}
S.filters=loadStoredFilters();S.filters.rampColors=cleanColors(S.filters.rampColors);S.filters.enabled=hasActiveFilters(S.filters);
function toast(m){E.toast.textContent=m;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),1800)}
function setTab(name){document.querySelectorAll('.tabBtn').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tabPanel').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));try{localStorage.setItem(TAB_KEY,name)}catch(e){}}
function snap(){return{cols:S.cols,rows:S.rows,interval:S.interval,curve:S.curve,curveVal:S.curveVal,scale:S.scale,ox:S.ox,oy:S.oy,tilt:S.tilt,frame:S.frame,dir:S.dir,mode:S.mode,bg:E.bg.value,filters:clone(S.filters)}}
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function histBtns(){E.undo.disabled=S.hist.length<=1;E.redo.disabled=!S.redo.length}
function commit(){if(!S.ready)return;const s=snap(),last=S.hist[S.hist.length-1];if(!same(s,last)){S.hist.push(s);if(S.hist.length>100)S.hist.shift();S.redo=[]}histBtns()}
function record(){if(!S.ready)return;const s=snap(),last=S.hist[S.hist.length-1];if(!same(s,last)){S.hist.push(s);if(S.hist.length>100)S.hist.shift()}histBtns()}
function restore(s){const was=S.playing;pause();Object.assign(S,s);S.filters=s.filters?Object.assign(defaultFilters(),clone(s.filters)):defaultFilters();S.filters.rampColors=cleanColors(S.filters.rampColors);S.filters.enabled=hasActiveFilters(S.filters);saveStoredFilters();E.bg.value=s.bg;sync();syncFilterUI();bg();if(S.img){draw();film()}else info();if(was)play();histBtns()}
function undo(){record();if(S.hist.length<=1){toast('되돌릴 내용이 없어');return}S.redo.push(S.hist.pop());restore(S.hist[S.hist.length-1]);toast('되돌렸어')}
function redo(){if(!S.redo.length){toast('다시 실행할 내용이 없어');return}const n=S.redo.pop();S.hist.push(n);restore(n);toast('다시 실행했어')}
function loaded(v){E.empty.style.display=v?'none':'block';E.preview.classList.toggle('on',v);[E.play,E.stop,E.prev,E.next,E.first,E.auto,E.save,E.zip,E.qAuto,E.qPlay,E.qSave,E.qZip].filter(Boolean).forEach(b=>b.disabled=!v)}
function sync(){E.cols.value=S.cols;E.rows.value=S.rows;E.interval.value=S.interval;E.curve.value=S.curve;E.curveVal.value=S.curveVal;E.scale.value=S.scale;E.scaleTxt.textContent=S.scale+'x';E.mode.value=S.mode;E.ox.value=S.ox;E.oy.value=S.oy;E.tilt.value=S.tilt;E.count.textContent=count();E.qPlay.textContent=S.playing?'정지':'재생';fills()}
function syncFilterUI(){const f=S.filters;f.rampColors=cleanColors(f.rampColors);f.enabled=hasActiveFilters(f);if(E.fEnable)E.fEnable.checked=f.enabled;E.fBypass.checked=f.bypass;E.fPixel.checked=f.pixel;E.fPixelSize.value=f.pixelSize;E.fPoster.checked=f.poster;E.fPosterSteps.value=f.posterSteps;E.fRamp.checked=f.ramp;E.fRampPreset.value=f.rampPreset;[E.fRampColor0,E.fRampColor1,E.fRampColor2,E.fRampColor3].forEach((el,i)=>{if(el)el.value=f.rampColors[i]});E.fDither.checked=f.dither;E.fDitherAmount.value=f.ditherAmount;E.fNoise.checked=f.noise;E.fNoiseAmount.value=f.noiseAmount;E.fOutline.checked=f.outline;E.fOutlineWidth.value=f.outlineWidth;E.fBloom.checked=f.bloom;E.fBloomAmount.value=f.bloomAmount;E.fChrom.checked=f.chrom;E.fChromAmount.value=f.chromAmount;E.fGlitch.checked=f.glitch;E.fGlitchAmount.value=f.glitchAmount;if(E.fFxSketch){E.fFxSketch.checked=f.fxSketch;E.fFxSketchPreset.value=f.fxSketchPreset;E.fFxSketchStrength.value=f.fxSketchStrength;E.fFxSketchSteps.value=f.fxSketchSteps;E.fFxSketchContrast.value=f.fxSketchContrast;E.fFxSketchEdge.value=f.fxSketchEdge;E.fFxSketchClean.value=f.fxSketchClean}drawRampSwatches()}
function readFilterUI(){const f=S.filters;f.bypass=E.fBypass.checked;f.pixel=E.fPixel.checked;f.pixelSize=clamp(E.fPixelSize.value,1,16);f.poster=E.fPoster.checked;f.posterSteps=clamp(E.fPosterSteps.value,2,16);f.ramp=E.fRamp.checked;f.rampPreset=E.fRampPreset.value;f.rampColors=cleanColors([E.fRampColor0?.value,E.fRampColor1?.value,E.fRampColor2?.value,E.fRampColor3?.value]);f.dither=E.fDither.checked;f.ditherAmount=clamp(E.fDitherAmount.value,0,100);f.noise=E.fNoise.checked;f.noiseAmount=clamp(E.fNoiseAmount.value,0,40);f.outline=E.fOutline.checked;f.outlineWidth=clamp(E.fOutlineWidth.value,1,4);f.bloom=E.fBloom.checked;f.bloomAmount=clamp(E.fBloomAmount.value,0,100);f.chrom=E.fChrom.checked;f.chromAmount=clamp(E.fChromAmount.value,0,12);f.glitch=E.fGlitch.checked;f.glitchAmount=clamp(E.fGlitchAmount.value,0,20);if(E.fFxSketch){f.fxSketch=E.fFxSketch.checked;f.fxSketchPreset=E.fFxSketchPreset.value;f.fxSketchStrength=clamp(E.fFxSketchStrength.value,0,100);f.fxSketchSteps=clamp(E.fFxSketchSteps.value,2,6);f.fxSketchContrast=clamp(E.fFxSketchContrast.value,0,100);f.fxSketchEdge=clamp(E.fFxSketchEdge.value,0,100);f.fxSketchClean=clamp(E.fFxSketchClean.value,0,100)}f.enabled=hasActiveFilters(f);if(E.fEnable)E.fEnable.checked=f.enabled;drawRampSwatches();saveStoredFilters()}
function drawRampSwatches(){E.rampSwatches.innerHTML='';for(const c of currentRampPalette()){const d=document.createElement('div');d.className='swatch';d.style.background=c;E.rampSwatches.appendChild(d)}}
function info(){const f=fs(),c=count();E.status.textContent=S.img?S.name:'이미지를 붙여넣거나 파일을 선택해줘';E.frameTxt.textContent=S.img?`Frame ${S.frame+1} / ${c}`:'Frame - / -';E.iFile.textContent=S.img?S.name:'-';E.iSheet.textContent=S.img?`${S.w} × ${S.h}`:'-';E.iFrame.textContent=S.img?`${r2(f.w)} × ${r2(f.h)}`:'-';E.iCount.textContent=S.img?c:'-';E.iFps.textContent=S.img?`${r2(1000/S.interval)} fps`:'-';E.iCurve.textContent=S.img?`${S.curve} ${S.curveVal}%`:'-';E.iOffset.textContent=S.img?`${S.ox}, ${S.oy}`:'-';E.iTilt.textContent=S.img?`${S.tilt}°`:'-';E.count.textContent=c}
function renderBase(targetCtx,frameIndex=S.frame){const c=count();const frame=((frameIndex%c)+c)%c;const f=fs(),col=frame%S.cols,row=Math.floor(frame/S.cols),bw=Math.max(1,Math.round(f.w)),bh=Math.max(1,Math.round(f.h)),rad=S.tilt*Math.PI/180,cs=Math.abs(Math.cos(rad)),sn=Math.abs(Math.sin(rad)),cw=Math.ceil(bw*cs+bh*sn+(Math.abs(S.ox)+24)*2),ch=Math.ceil(bw*sn+bh*cs+(Math.abs(S.oy)+24)*2);targetCtx.canvas.width=cw;targetCtx.canvas.height=ch;targetCtx.imageSmoothingEnabled=false;targetCtx.clearRect(0,0,cw,ch);targetCtx.save();targetCtx.translate(cw/2+S.ox,ch/2+S.oy);targetCtx.rotate(rad);targetCtx.drawImage(S.img,col*f.w,row*f.h,f.w,f.h,-bw/2,-bh/2,bw,bh);targetCtx.restore();return{w:cw,h:ch,frame}}
function renderFrameCanvas(frameIndex,filtered=true){const ex=document.createElement('canvas'),exCtx=ex.getContext('2d',{willReadFrequently:true});renderBase(exCtx,frameIndex);if(!filtered)return ex;const out=document.createElement('canvas');applyFilters(ex,out,S.filters,frameIndex,true);return out}
function draw(){if(!S.img)return;const b=renderBase(baseCtx,S.frame);E.canvas.width=b.w;E.canvas.height=b.h;E.canvas.style.width=Math.round(b.w*S.scale)+'px';E.canvas.style.height=Math.round(b.h*S.scale)+'px';applyFilters(BASE,E.canvas,S.filters,S.frame,false);info();active();fills()}
function film(){E.film.innerHTML='';if(!S.img)return;const c=count(),f=fs(),n=Math.min(c,144);for(let i=0;i<n;i++){const cn=document.createElement('canvas'),col=i%S.cols,row=Math.floor(i/S.cols);cn.width=96;cn.height=96;const x=cn.getContext('2d');x.imageSmoothingEnabled=false;const fit=Math.min(96/f.w,96/f.h),dw=Math.max(1,f.w*fit),dh=Math.max(1,f.h*fit);x.drawImage(S.img,col*f.w,row*f.h,f.w,f.h,(96-dw)/2,(96-dh)/2,dw,dh);const b=document.createElement('button');b.className='thumb';b.dataset.i=i;b.innerHTML=`<img src="${cn.toDataURL('image/png')}" alt=""><span>${i+1}</span>`;b.onclick=()=>{S.frame=i;pause();draw()};E.film.appendChild(b)}active()}
function active(){E.film.querySelectorAll('.thumb').forEach(t=>t.classList.toggle('active',+t.dataset.i===S.frame))}
function doAutoGrid(silent=false){if(!S.img)return;try{const best=smartDetect(S.img);S.cols=best.cols;S.rows=best.rows;S.frame=0;sync();draw();film();commit();if(!silent)toast(`${S.cols} × ${S.rows}로 추정했어 · 사용 프레임 ${best.used}/${S.cols*S.rows}`);return best}catch(e){console.error(e);toast('자동추정 중 오류가 났어')}}
function step(){const c=count();if(c<=1)return;if(S.mode==='pingpong'){const n=S.frame+S.dir;if(n>=c){S.dir=-1;S.frame=Math.max(0,c-2)}else if(n<0){S.dir=1;S.frame=Math.min(1,c-1)}else S.frame=n}else if(S.mode==='once'){if(S.frame>=c-1){pause();return}S.frame++}else S.frame=(S.frame+1)%c;draw()}
function curveDelay(){const base=clamp(S.interval,10,100),c=count(),t=c<=1?0:S.frame/(c-1),a=clamp(S.curveVal,0,100)/100;let m=1;if(S.curve==='easeIn')m=1.7-1.2*t;else if(S.curve==='easeOut')m=.5+1.2*t;else if(S.curve==='easeInOut')m=.55+1.45*Math.abs(2*t-1);else if(S.curve==='burst')m=t<.32?1.75:t<.72?.48:1.15;return Math.round(clamp(base*((1-a)+a*m),4,220))}
function schedule(){if(!S.playing)return;S.timer=setTimeout(()=>{step();schedule()},curveDelay())}
function play(){if(!S.img)return;pause(false);S.playing=true;E.play.textContent='재생 중';E.qPlay.textContent='정지';schedule()}
function pause(btn=true){if(S.timer){clearTimeout(S.timer);S.timer=null}S.playing=false;if(btn){E.play.textContent='재생';E.qPlay.textContent='재생'}}
function restart(){if(S.playing)play()}
function sheet(rebuild=false){S.cols=clamp(E.cols.value,1,12);S.rows=clamp(E.rows.value,1,12);S.frame=Math.min(S.frame,count()-1);sync();draw();if(rebuild)film()}
function playback(){S.interval=clamp(E.interval.value,10,100);S.curve=E.curve.value;S.curveVal=clamp(E.curveVal.value,0,100);S.mode=E.mode.value;sync();info();restart()}
function trans(){S.ox=clamp(E.ox.value,-128,128);S.oy=clamp(E.oy.value,-128,128);S.tilt=clamp(E.tilt.value,-180,180);sync();draw()}
function scale(){S.scale=clamp(E.scale.value,1,10);sync();draw()}
function bg(){E.stage.className='stage '+(E.bg.value==='checker'?'':E.bg.value)}
function reset(){pause();Object.assign(S,{cols:3,rows:3,interval:83,curve:'linear',curveVal:50,scale:3,ox:0,oy:0,tilt:0,frame:0,dir:1,mode:'loop'});S.filters=defaultFilters();S.filters.rampColors=cleanColors(S.filters.rampColors);S.filters.enabled=false;saveStoredFilters();sync();syncFilterUI();bg();draw();film();commit();toast('초기화했어')}
function load(file,opts={autoDetect:true}){if(!file||!file.type.startsWith('image/')){toast('이미지 파일만 가능해');return}pause();if(S.url)URL.revokeObjectURL(S.url);const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{Object.assign(S,{img,url,name:file.name||'Pasted Image',w:img.naturalWidth,h:img.naturalHeight,frame:0,dir:1});loaded(true);S.ready=true;sync();syncFilterUI();bg();if(opts.autoDetect!==false){doAutoGrid(true);toast(`이미지 로드 완료 · ${S.cols} × ${S.rows} 자동추정`)}else{draw();film();toast('이미지 로드 완료')}S.hist=[snap()];S.redo=[];histBtns();play()};img.onerror=()=>toast('이미지를 읽지 못했어');img.src=url}
function save(){if(!S.img)return;saveCanvasPNG(renderFrameCanvas(S.frame,true),`sprite-frame-${String(S.frame+1).padStart(3,'0')}.png`)}
async function zipSave(){if(!S.img)return;const total=count();const was=S.playing;pause();toast(`ZIP 생성 중 0/${total}`);try{await saveFramesZip({frameCount:total,filename:`${(S.name||'sprite').replace(/\.[^.]+$/,'')}-frames.zip`,prefix:'frame',renderFrame:i=>renderFrameCanvas(i,true),onProgress:(i,n)=>{if(i===n||i%5===0)toast(`ZIP 생성 중 ${i}/${n}`)}});toast(`ZIP 저장 완료 · ${total}프레임`)}catch(e){console.error(e);toast('ZIP 저장 중 오류가 났어')}if(was)play()}
function fills(){document.querySelectorAll('.scrub').forEach(z=>{const i=$(z.dataset.target),min=+(z.dataset.min||i.min||1),max=+(z.dataset.max||i.max||100),v=clamp(i.value,min,max),f=z.querySelector('.fill');if(f)f.style.width=Math.max(0,Math.min(100,(v-min)/(max-min)*100))+'%'})}
function applyId(id,final=false){if(id==='cols'||id==='rows')sheet(final);else if(id==='interval'||id==='curveVal')playback();else trans()}
function scrubs(){document.querySelectorAll('.scrub').forEach(z=>z.onpointerdown=e=>{const i=$(z.dataset.target);e.preventDefault();z.setPointerCapture(e.pointerId);z.classList.add('dragging');const min=+(z.dataset.min||i.min||1),max=+(z.dataset.max||i.max||100),st=+(z.dataset.step||1),sx=e.clientX,raw=num(i.value),sv=raw===null?min:raw;let moved=false,last=sv;const move=ev=>{const next=clamp(sv+Math.round((ev.clientX-sx)/10*(ev.shiftKey?4:1))*st,min,max);if(next!==last){last=next;moved=true;i.value=next;applyId(z.dataset.target,false)}};const up=()=>{z.classList.remove('dragging');applyId(z.dataset.target,true);if(moved)commit();z.removeEventListener('pointermove',move);z.removeEventListener('pointerup',up);z.removeEventListener('pointercancel',up)};z.addEventListener('pointermove',move);z.addEventListener('pointerup',up);z.addEventListener('pointercancel',up)});fills()}
function bindNum(i,fn){let last=0;i.oninput=fn;i.onchange=()=>{fn();commit()};i.onblur=commit;i.onkeydown=e=>{if(e.key==='Enter'){const now=Date.now();if(now-last<500){e.preventDefault();i.select();toast('전체 선택했어');last=0}else last=now}}}
function bindFilter(el){if(!el)return;el.oninput=()=>{if([E.fRampColor0,E.fRampColor1,E.fRampColor2,E.fRampColor3].includes(el)){E.fRampPreset.value='custom'}readFilterUI();draw()};el.onchange=()=>{if([E.fRampColor0,E.fRampColor1,E.fRampColor2,E.fRampColor3].includes(el)){E.fRampPreset.value='custom'}readFilterUI();draw();commit()}}
function fileFromClip(dt){if(!dt)return null;for(const f of dt.files||[])if(f.type&&f.type.startsWith('image/'))return f;for(const it of dt.items||[])if(it.type&&it.type.startsWith('image/')){const f=it.getAsFile();if(f)return f}return null}
function onPaste(e){const f=fileFromClip(e.clipboardData);if(f){e.preventDefault();e.stopPropagation();load(f,{autoDetect:true})}else toast('클립보드에서 이미지를 찾지 못했어')}
async function readClipboard(){try{if(!navigator.clipboard||!navigator.clipboard.read){toast('브라우저가 클립보드 읽기를 막고 있어');return}const items=await navigator.clipboard.read();for(const item of items)for(const type of item.types)if(type.startsWith('image/')){const blob=await item.getType(type);load(new File([blob],'clipboard-image.png',{type}),{autoDetect:true});return}toast('클립보드에 이미지가 없어')}catch(e){toast('클립보드 권한이 막혔어. Ctrl+V로 시도해줘')}}
E.pick.onclick=()=>E.file.click();E.file.onchange=e=>{const f=e.target.files?.[0];if(f)load(f,{autoDetect:true});e.target.value=''};
E.clip.onclick=readClipboard;E.undo.onclick=undo;E.redo.onclick=redo;E.reset.onclick=reset;E.play.onclick=play;E.stop.onclick=()=>pause();E.prev.onclick=()=>{pause();S.frame=(S.frame-1+count())%count();draw()};E.next.onclick=()=>{pause();S.frame=(S.frame+1)%count();draw()};E.first.onclick=()=>{pause();S.frame=0;S.dir=1;draw()};E.qAuto.onclick=()=>doAutoGrid(false);E.qPlay.onclick=()=>S.playing?pause():play();E.qSave.onclick=save;E.qZip.onclick=zipSave;E.qPreset.onclick=()=>E.fPreset.click();
bindNum(E.cols,()=>sheet(false));bindNum(E.rows,()=>sheet(false));bindNum(E.interval,playback);bindNum(E.curveVal,playback);bindNum(E.ox,trans);bindNum(E.oy,trans);bindNum(E.tilt,trans);
E.curve.onchange=()=>{playback();commit()};E.mode.onchange=()=>{playback();commit()};E.scale.oninput=scale;E.scale.onchange=commit;E.bg.onchange=()=>{bg();commit()};E.auto.onclick=()=>doAutoGrid(false);E.save.onclick=save;if(E.zip)E.zip.onclick=zipSave;
[E.fEnable,E.fBypass,E.fPixel,E.fPixelSize,E.fPoster,E.fPosterSteps,E.fRamp,E.fRampPreset,E.fRampColor0,E.fRampColor1,E.fRampColor2,E.fRampColor3,E.fDither,E.fDitherAmount,E.fNoise,E.fNoiseAmount,E.fOutline,E.fOutlineWidth,E.fBloom,E.fBloomAmount,E.fChrom,E.fChromAmount,E.fGlitch,E.fGlitchAmount,E.fFxSketch,E.fFxSketchPreset,E.fFxSketchStrength,E.fFxSketchSteps,E.fFxSketchContrast,E.fFxSketchEdge,E.fFxSketchClean].forEach(bindFilter);
E.fReset.onclick=()=>{S.filters=defaultFilters();S.filters.rampColors=cleanColors(S.filters.rampColors);S.filters.enabled=false;saveStoredFilters();syncFilterUI();draw();commit();toast('필터 초기화')};
E.fPreset.onclick=()=>{const p=FILTER_PRESETS[S.presetIndex%FILTER_PRESETS.length];S.presetIndex++;S.filters=Object.assign(defaultFilters(),clone(p[1]));S.filters.rampColors=cleanColors(S.filters.rampColors);S.filters.enabled=hasActiveFilters(S.filters);saveStoredFilters();syncFilterUI();draw();commit();toast(`프리셋 적용: ${p[0]}`)};
document.querySelectorAll('.tabBtn').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.addEventListener('paste',onPaste,true);window.addEventListener('paste',onPaste,true);
['dragenter','dragover'].forEach(n=>window.addEventListener(n,e=>{e.preventDefault();E.card.classList.add('drag')}));
['dragleave','drop'].forEach(n=>window.addEventListener(n,e=>{e.preventDefault();if(n==='drop'){const f=e.dataTransfer?.files?.[0];if(f)load(f,{autoDetect:true})}E.card.classList.remove('drag')}));
window.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.code==='KeyZ'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.code==='KeyY'){e.preventDefault();redo();return}const edit=e.target&&['INPUT','SELECT'].includes(e.target.tagName);if(!S.img||edit)return;if(e.code==='Space'){e.preventDefault();S.playing?pause():play()}if(e.code==='ArrowLeft'){e.preventDefault();E.prev.click()}if(e.code==='ArrowRight'){e.preventDefault();E.next.click()}};
loaded(false);sync();syncFilterUI();info();bg();scrubs();histBtns();setTab(localStorage.getItem(TAB_KEY)||'playback');E.stage.focus();
