import {applyFxSketch} from './stylize.js';
export const RAMPS={fire:['#12020a','#8b1026','#ff6a00','#ffd166'],ice:['#07111f','#145da0','#7de2ff','#ffffff'],toxic:['#06120a','#1f7a1f','#9cff00','#f7ffb6'],mono:['#000000','#4b5563','#d1d5db','#ffffff']};
export function defaultFilters(){return{enabled:false,bypass:false,pixel:false,pixelSize:4,poster:false,posterSteps:5,ramp:false,rampPreset:'fire',rampColors:['#12020a','#8b1026','#ff6a00','#ffd166'],dither:false,ditherAmount:45,noise:false,noiseAmount:8,outline:false,outlineWidth:1,bloom:false,bloomAmount:45,chrom:false,chromAmount:3,glitch:false,glitchAmount:5,fxSketch:false,fxSketchPreset:'generic',fxSketchStrength:75,fxSketchSteps:4,fxSketchContrast:60,fxSketchEdge:60,fxSketchClean:35}}
export const FILTER_PRESETS=[['Cel FX',{enabled:true,poster:true,posterSteps:5,outline:true,outlineWidth:1}],['Pixel Art',{enabled:true,pixel:true,pixelSize:4,poster:true,posterSteps:6,dither:true,ditherAmount:28}],['Fire Ramp',{enabled:true,poster:true,posterSteps:7,ramp:true,rampPreset:'fire',dither:true,ditherAmount:22,noise:true,noiseAmount:5,bloom:true,bloomAmount:55}],['Ice Bloom',{enabled:true,ramp:true,rampPreset:'ice',outline:true,outlineWidth:1,bloom:true,bloomAmount:70,chrom:true,chromAmount:2}],['Toxic Dither',{enabled:true,poster:true,posterSteps:4,ramp:true,rampPreset:'toxic',dither:true,ditherAmount:65,noise:true,noiseAmount:9,bloom:true,bloomAmount:38}],['Glitch',{enabled:true,pixel:true,pixelSize:2,poster:true,posterSteps:8,noise:true,noiseAmount:12,chrom:true,chromAmount:5,glitch:true,glitchAmount:11}],['FX Sketch',{enabled:true,fxSketch:true,fxSketchPreset:'generic',fxSketchStrength:85,fxSketchSteps:4,fxSketchContrast:65,fxSketchEdge:70,fxSketchClean:35}],['Custom Ramp',{enabled:true,ramp:true,rampPreset:'custom',rampColors:['#080014','#3b1b8f','#00d4ff','#ffffff'],poster:true,posterSteps:8,bloom:true,bloomAmount:35}]];
const hexToRgb=h=>{h=(h||'#000000').replace('#','');if(h.length===3)h=h.split('').map(v=>v+v).join('');return[parseInt(h.slice(0,2),16)||0,parseInt(h.slice(2,4),16)||0,parseInt(h.slice(4,6),16)||0]};
const lerp=(a,b,t)=>a+(b-a)*t;
function rampColor(t,pal){pal=pal&&pal.length?pal:RAMPS.fire;const n=pal.length-1,x=Math.max(0,Math.min(1,t))*n,i=Math.min(n-1,Math.floor(x)),f=x-i,a=hexToRgb(pal[i]),b=hexToRgb(pal[i+1]);return[lerp(a[0],b[0],f),lerp(a[1],b[1],f),lerp(a[2],b[2],f)]}
function outlineImage(img,w,h,width){const src=new Uint8ClampedArray(img.data),out=new ImageData(new Uint8ClampedArray(img.data),w,h),d=out.data,rad=Math.max(1,width|0);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;if(src[i+3]>12)continue;let hit=false;for(let yy=-rad;yy<=rad&&!hit;yy++)for(let xx=-rad;xx<=rad;xx++){const nx=x+xx,ny=y+yy;if(nx<0||ny<0||nx>=w||ny>=h)continue;if(src[(ny*w+nx)*4+3]>40){hit=true;break}}if(hit){d[i]=0;d[i+1]=0;d[i+2]=0;d[i+3]=210}}return out}
function drawBloom(dst,amount){const dctx=dst.getContext('2d'),tmp=document.createElement('canvas'),t=tmp.getContext('2d');tmp.width=dst.width;tmp.height=dst.height;t.filter='brightness(1.35) blur('+Math.max(1,Math.round(amount/18))+'px)';t.drawImage(dst,0,0);dctx.save();dctx.globalCompositeOperation='lighter';dctx.globalAlpha=Math.min(.9,amount/100);dctx.drawImage(tmp,0,0);dctx.restore()}
function drawChromatic(dst,amount){const dctx=dst.getContext('2d',{willReadFrequently:true}),src=dctx.getImageData(0,0,dst.width,dst.height),out=dctx.createImageData(dst.width,dst.height),s=src.data,d=out.data,off=Math.round(amount);for(let y=0;y<dst.height;y++)for(let x=0;x<dst.width;x++){const i=(y*dst.width+x)*4,ri=(y*dst.width+Math.max(0,Math.min(dst.width-1,x-off)))*4,bi=(y*dst.width+Math.max(0,Math.min(dst.width-1,x+off)))*4;d[i]=s[ri];d[i+1]=s[i+1];d[i+2]=s[bi+2];d[i+3]=s[i+3]}dctx.putImageData(out,0,0)}
function drawGlitch(dst,amount,frame){const dctx=dst.getContext('2d'),tmp=document.createElement('canvas'),t=tmp.getContext('2d');tmp.width=dst.width;tmp.height=dst.height;t.drawImage(dst,0,0);const slices=Math.max(1,Math.round(amount));for(let i=0;i<slices;i++){const y=Math.floor((Math.sin(i*97+frame*13)*.5+.5)*dst.height),h=Math.max(1,Math.floor(dst.height/(12+i%6))),dx=Math.round(Math.sin(i*33+frame*7)*amount);dctx.clearRect(0,y,dst.width,h);dctx.drawImage(tmp,0,y,dst.width,h,dx,y,dst.width,h)}}
export function getRampPalette(filters){return filters.rampPreset==='custom'?(filters.rampColors||RAMPS.fire):(RAMPS[filters.rampPreset]||RAMPS.fire)}
export function applyFilters(src,dst,filters,frame=0,forceSave=false){dst.width=src.width;dst.height=src.height;const dctx=dst.getContext('2d',{willReadFrequently:true});dctx.imageSmoothingEnabled=false;dctx.clearRect(0,0,dst.width,dst.height);dctx.drawImage(src,0,0);const f=filters;if(!f.enabled||f.bypass)return;if(f.pixel&&f.pixelSize>1){const step=f.pixelSize,tmp=document.createElement('canvas'),tw=Math.max(1,Math.ceil(dst.width/step)),th=Math.max(1,Math.ceil(dst.height/step)),tctx=tmp.getContext('2d');tmp.width=tw;tmp.height=th;tctx.imageSmoothingEnabled=false;tctx.drawImage(dst,0,0,tw,th);dctx.clearRect(0,0,dst.width,dst.height);dctx.imageSmoothingEnabled=false;dctx.drawImage(tmp,0,0,tw,th,0,0,dst.width,dst.height)}if(f.bloom)drawBloom(dst,f.bloomAmount);if(f.chrom)drawChromatic(dst,f.chromAmount);if(f.glitch)drawGlitch(dst,f.glitchAmount,frame);let img=dctx.getImageData(0,0,dst.width,dst.height);if(f.outline)img=outlineImage(img,dst.width,dst.height,f.outlineWidth);let data=img.data;const bayer=[0,8,2,10,12,4,6,14,3,11,1,9,15,7,13,5],pal=getRampPalette(f),noiseSeed=((frame||0)*101)%100000;for(let y=0;y<dst.height;y++)for(let x=0;x<dst.width;x++){const i=(y*dst.width+x)*4;if(data[i+3]===0)continue;let r=data[i],g=data[i+1],b=data[i+2];if(f.ramp){const lum=(r*.299+g*.587+b*.114)/255,rc=rampColor(lum,pal);r=rc[0];g=rc[1];b=rc[2]}if(f.poster){const st=Math.max(1,f.posterSteps-1);r=Math.round(Math.round(r/255*st)/st*255);g=Math.round(Math.round(g/255*st)/st*255);b=Math.round(Math.round(b/255*st)/st*255)}if(f.dither){const amt=f.ditherAmount/100,th=(bayer[(x&3)+(y&3)*4]/16-.5)*64*amt;r+=th;g+=th;b+=th}if(f.noise){const n=((Math.sin((x*12.9898+y*78.233+noiseSeed)*43758.5453)%1)*2-1)*f.noiseAmount;r+=n;g+=n;b+=n}data[i]=Math.max(0,Math.min(255,r));data[i+1]=Math.max(0,Math.min(255,g));data[i+2]=Math.max(0,Math.min(255,b))}dctx.putImageData(img,0,0);applyFxSketch(dst,f)}
