const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function makeMask(img){const c=document.createElement('canvas');c.width=img.naturalWidth||img.width;c.height=img.naturalHeight||img.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data,w=c.width,h=c.height,corner=[[0,0],[w-1,0],[0,h-1],[w-1,h-1]];let br=0,bg=0,bb=0,ba=0;for(const[p,q]of corner){const i=(q*w+p)*4;br+=d[i];bg+=d[i+1];bb+=d[i+2];ba+=d[i+3]}br/=4;bg/=4;bb/=4;ba/=4;const trans=ba<16,m=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let xx=0;xx<w;xx++){const i=(y*w+xx)*4,r=d[i],g=d[i+1],b=d[i+2],a=d[i+3];let fg=false;if(trans)fg=a>20;else{const dist=Math.abs(r-br)+Math.abs(g-bg)+Math.abs(b-bb)+Math.abs(a-ba);fg=a>20&&dist>30}m[y*w+xx]=fg?1:0}return{mask:m,width:w,height:h}}
function dilateMask(mask,w,h,rx=1,ry=1){const out=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let hit=0;for(let yy=Math.max(0,y-ry);yy<=Math.min(h-1,y+ry)&&!hit;yy++)for(let xx=Math.max(0,x-rx);xx<=Math.min(w-1,x+rx);xx++)if(mask[yy*w+xx]){hit=1;break}out[y*w+x]=hit}return out}
function erodeMask(mask,w,h,rx=1,ry=1){const out=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let ok=1;for(let yy=Math.max(0,y-ry);yy<=Math.min(h-1,y+ry)&&ok;yy++)for(let xx=Math.max(0,x-rx);xx<=Math.min(w-1,x+rx);xx++)if(!mask[yy*w+xx]){ok=0;break}out[y*w+x]=ok}return out}
function closeMask(mask,w,h,rx=1,ry=1){return erodeMask(dilateMask(mask,w,h,rx,ry),w,h,rx,ry)}
function extractComponents(mask,w,h,minSize=18){const seen=new Uint8Array(w*h),comps=[];for(let i=0;i<w*h;i++){if(!mask[i]||seen[i])continue;const stack=[i];seen[i]=1;let size=0,minX=w,maxX=0,minY=h,maxY=0,sumX=0,sumY=0;while(stack.length){const cur=stack.pop(),x=cur%w,y=(cur/w)|0;size++;sumX+=x;sumY+=y;if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y;const ns=[];if(x>0)ns.push(cur-1);if(x<w-1)ns.push(cur+1);if(y>0)ns.push(cur-w);if(y<h-1)ns.push(cur+w);for(const n of ns)if(mask[n]&&!seen[n]){seen[n]=1;stack.push(n)}}if(size>=minSize)comps.push({size,x0:minX,y0:minY,x1:maxX,y1:maxY,w:maxX-minX+1,h:maxY-minY+1,cx:sumX/size,cy:sumY/size})}comps.sort((a,b)=>b.size-a.size);return comps}
function pickMajorComponents(comps){if(!comps.length)return[];const largest=comps[0].size,major=comps.filter(c=>c.size>=Math.max(18,largest*.12));return major.length?major:comps.slice(0,Math.min(comps.length,24))}
const median=arr=>{if(!arr.length)return 0;const s=[...arr].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
function cluster1D(values,gap){if(!values.length)return[];const sorted=[...values].sort((a,b)=>a-b),groups=[[sorted[0]]];for(let i=1;i<sorted.length;i++){const g=groups[groups.length-1];if(sorted[i]-g[g.length-1]<=gap)g.push(sorted[i]);else groups.push([sorted[i]])}return groups}
function bandOcc(mask,w,h,axis,pos,half=1){let n=0,t=0;if(axis==='x'){const a=Math.max(0,pos-half),b=Math.min(w-1,pos+half);for(let y=0;y<h;y++)for(let x=a;x<=b;x++){t++;n+=mask[y*w+x]}}else{const a=Math.max(0,pos-half),b=Math.min(h-1,pos+half);for(let y=a;y<=b;y++)for(let x=0;x<w;x++){t++;n+=mask[y*w+x]}}return t?n/t:1}
function smooth1D(arr,radius=2){const out=new Array(arr.length).fill(0);for(let i=0;i<arr.length;i++){let s=0,c=0;for(let j=Math.max(0,i-radius);j<=Math.min(arr.length-1,i+radius);j++){s+=arr[j];c++}out[i]=c?s/c:0}return out}
function projection(mask,w,h,axis){const n=axis==='x'?w:h,arr=new Array(n).fill(0);if(axis==='x'){for(let x=0;x<w;x++){let s=0;for(let y=0;y<h;y++)s+=mask[y*w+x];arr[x]=s/h}}else{for(let y=0;y<h;y++){let s=0;for(let x=0;x<w;x++)s+=mask[y*w+x];arr[y]=s/w}}return arr}
function projectionPeaks(profile,minDist){const sm=smooth1D(profile,3),mx=Math.max(...sm,0),raw=[];if(mx<=0)return[];for(let i=1;i<sm.length-1;i++)if(sm[i]>=mx*.28&&sm[i]>=sm[i-1]&&sm[i]>=sm[i+1])raw.push([i,sm[i]]);const picked=[];for(const p of raw.sort((a,b)=>b[1]-a[1]))if(picked.every(q=>Math.abs(q[0]-p[0])>=minDist))picked.push(p);return picked.sort((a,b)=>a[0]-b[0])}
function stripHint(mask,w,h,comps){const major=pickMajorComponents(comps);if(major.length<4)return null;const px=projection(mask,w,h,'x'),py=projection(mask,w,h,'y'),xp=projectionPeaks(px,Math.max(12,Math.round(w/18))),yp=projectionPeaks(py,Math.max(12,Math.round(h/18))),xClusters=cluster1D(major.map(c=>c.cx),Math.max(10,w*.08)),yClusters=cluster1D(major.map(c=>c.cy),Math.max(10,h*.12)),medAspectW=median(major.map(c=>c.w/Math.max(1,c.h))),medAspectH=median(major.map(c=>c.h/Math.max(1,c.w))),medH=median(major.map(c=>c.h))/h,medW=median(major.map(c=>c.w))/w;if(yClusters.length<=1&&xClusters.length>=4&&Math.abs(xp.length-xClusters.length)<=1&&medAspectH>1.45&&medH>.55)return{cols:clamp(xClusters.length,1,12),rows:1,strength:3};if(xClusters.length<=1&&yClusters.length>=4&&Math.abs(yp.length-yClusters.length)<=1&&medAspectW>1.45&&medW>.55)return{cols:1,rows:clamp(yClusters.length,1,12),strength:3};return null}
function cellBounds(col,row,cols,rows,w,h){const cw=w/cols,ch=h/rows,x0=Math.round(col*cw),x1=Math.round((col+1)*cw),y0=Math.round(row*ch),y1=Math.round((row+1)*ch);return{x0,x1,y0,y1,w:Math.max(1,x1-x0),h:Math.max(1,y1-y0)}}
function usedFrames(mask,w,h,cols,rows){let last=-1;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const b=cellBounds(c,r,cols,rows,w,h);let occ=0;for(let y=b.y0;y<b.y1;y++)for(let x=b.x0;x<b.x1;x++)occ+=mask[y*w+x];if(occ>Math.max(10,b.w*b.h*.0012))last=r*cols+c}return Math.max(1,last+1)}
function strongSeparators(mask,w,h,axis){const size=axis==='x'?w:h,pos=new Set();for(let d=2;d<=12;d++){const cell=size/d;if(cell<18)continue;const vals=[];for(let k=1;k<d;k++)vals.push(bandOcc(mask,w,h,axis,Math.round(k*cell),1));if(!vals.length)continue;const avg=vals.reduce((a,b)=>a+b,0)/vals.length,mx=Math.max(...vals);if(avg<0.045&&mx<0.09)for(let k=1;k<d;k++)pos.add(Math.round(k*cell))}return[...pos]}
function separatorDivision(mask,w,h,axis){const size=axis==='x'?w:h,other=axis==='x'?h:w;let best=null;for(let d=2;d<=12;d++){const cell=size/d;if(cell<18)continue;const vals=[];for(let k=1;k<d;k++)vals.push(bandOcc(mask,w,h,axis,Math.round(k*cell),2));if(!vals.length)continue;const avg=vals.reduce((a,b)=>a+b,0)/vals.length,mx=Math.max(...vals),score=avg*11+mx*5-d*.055;const strong=avg<0.035&&mx<0.085;const veryStrong=avg<0.018&&mx<0.055;if((strong||veryStrong)&&(!best||score<best.score))best={d,avg,max:mx,score,strength:veryStrong?4:3}}return best}
function separatorGridHint(mask,w,h,major){const x=separatorDivision(mask,w,h,'x'),y=separatorDivision(mask,w,h,'y');let cols=x?.d||1,rows=y?.d||1,strength=Math.max(x?.strength||0,y?.strength||0);const xClusters=cluster1D(major.map(c=>c.cx),Math.max(10,w*.08)).length,yClusters=cluster1D(major.map(c=>c.cy),Math.max(10,h*.08)).length;if(rows>=4&&(!x||cols<=2)&&h>w*1.25){cols=1;strength+=2}if(cols>=4&&(!y||rows<=2)&&w>h*1.25){rows=1;strength+=2}if(cols===1&&rows===1)return null;if(rows>1&&yClusters>1)strength+=1;if(cols>1&&xClusters>1)strength+=1;return{cols:clamp(cols,1,12),rows:clamp(rows,1,12),strength}}
function countPeaks1D(arr){if(!arr.length)return 0;const sm=smooth1D(arr,1),maxv=Math.max(...sm);if(maxv<=0)return 0;const minPeak=Math.max(2,maxv*.35),minGap=Math.max(3,Math.round(arr.length*.08));let peaks=0,last=-9999,lastVal=0;for(let i=1;i<sm.length-1;i++){if(sm[i]>=minPeak&&sm[i]>=sm[i-1]&&sm[i]>=sm[i+1]){if(i-last>=minGap){peaks++;last=i;lastVal=sm[i]}else if(sm[i]>lastVal){last=i;lastVal=sm[i]}}}return peaks}
function multiPeakPenalty(mask,w,h,cols,rows){let penalty=0,checked=0;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const b=cellBounds(c,r,cols,rows,w,h),histX=new Array(b.w).fill(0),histY=new Array(b.h).fill(0);let occ=0;for(let y=b.y0;y<b.y1;y++)for(let x=b.x0;x<b.x1;x++){const v=mask[y*w+x];if(!v)continue;occ++;histX[x-b.x0]++;histY[y-b.y0]++}if(occ<8)continue;const px=countPeaks1D(histX),py=countPeaks1D(histY);if(px>1)penalty+=(px-1)*1.0;if(py>1)penalty+=(py-1)*1.35;checked++}return checked?penalty/checked:0}
function estimateComponentGrid(comps,w,h){if(!comps.length)return{cols:1,rows:1};const src=pickMajorComponents(comps);function best(axis){const size=axis==='x'?w:h,vals=src.map(c=>axis==='x'?c.cx:c.cy);let best=1,bestScore=Infinity;for(let d=1;d<=12;d++){const cell=size/d;let score=0;for(const v of vals){const b=Math.max(0,Math.min(d-1,Math.floor(v/cell))),center=(b+.5)*cell;score+=Math.abs(v-center)/(cell*.75+1e-6)}score/=Math.max(1,vals.length);score+=Math.max(0,(20-cell)/20)*2;if(d>src.length*1.5)score+=(d/src.length-1.5)*2.2;if(score<bestScore){bestScore=score;best=d}}return best}return{cols:best('x'),rows:best('y')}}
function axisScore(mask,w,h,d,axis,strong){const size=axis==='x'?w:h,cell=size/d,selected=[];let boundary=0;if(d>1){for(let k=1;k<d;k++){const p=Math.round(k*cell);selected.push(p);boundary+=bandOcc(mask,w,h,axis,p,1)}boundary/=selected.length}let missed=0;for(const p of strong)if(!selected.some(s=>Math.abs(s-p)<=2))missed++;const tiny=Math.max(0,(20-cell)/20);return boundary*7+missed*.75+tiny*3+d*.01}
function sizePreferencePenalty(cw,ch){const minDim=Math.min(cw,ch),maxDim=Math.max(cw,ch);let p=0;if(minDim<20)p+=(20-minDim)/5;if(minDim<32)p+=(32-minDim)/16;if(maxDim>260)p+=(maxDim-260)/180;return p}
function gridScore(mask,w,h,cols,rows){let holes=0;const active=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const b=cellBounds(c,r,cols,rows,w,h);let occ=0;for(let y=b.y0;y<b.y1;y++)for(let x=b.x0;x<b.x1;x++)occ+=mask[y*w+x];active.push(occ>Math.max(10,b.w*b.h*.0012)?1:0)}const last=active.lastIndexOf(1);if(last>=0)for(let i=0;i<=last;i++)if(!active[i])holes++;return holes*.7}
function centerAlignmentPenalty(comps,w,h,cols,rows){if(!comps.length)return 0;const cw=w/cols,ch=h/rows;let sum=0,total=0;for(const comp of comps){const col=Math.max(0,Math.min(cols-1,Math.floor(comp.cx/cw))),row=Math.max(0,Math.min(rows-1,Math.floor(comp.cy/ch))),ccx=(col+.5)*cw,ccy=(row+.5)*ch,dx=Math.abs(comp.cx-ccx)/(cw*.75+1e-6),dy=Math.abs(comp.cy-ccy)/(ch*.75+1e-6),wgt=Math.max(1,Math.sqrt(comp.size));sum+=wgt*(dx+dy);total+=wgt}return total?sum/total:0}
function overSegPenalty(cols,rows,majorCount,guessCols,guessRows){const cells=cols*rows;let p=0;if(cells>majorCount*1.75)p+=(cells/majorCount-1.75)*4.2;if(cols>guessCols*1.75)p+=(cols/Math.max(1,guessCols)-1.75)*2.6;if(rows>guessRows*1.75)p+=(rows/Math.max(1,guessRows)-1.75)*2.6;return p}
function tinyOccupancyPenalty(mask,w,h,cols,rows){let tiny=0,active=0;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const b=cellBounds(c,r,cols,rows,w,h);let occ=0;for(let y=b.y0;y<b.y1;y++)for(let x=b.x0;x<b.x1;x++)occ+=mask[y*w+x];const ratio=occ/Math.max(1,b.w*b.h);if(occ>6){active++;if(ratio<.015)tiny++}}return active?tiny/active*2.8:0}
function boundaryCutPenalty(mask,w,h,cols,rows){let penalty=0,checks=0;if(cols>1){const cw=w/cols;for(let k=1;k<cols;k++){const x=Math.round(k*cw);let both=0,total=0;for(let y=0;y<h;y++){const l=x>0?mask[y*w+x-1]:0,r=x<w?mask[y*w+Math.min(w-1,x)]:0;total++;if(l&&r)both++}penalty+=both/Math.max(1,total)*2;checks++}}if(rows>1){const ch=h/rows;for(let k=1;k<rows;k++){const y=Math.round(k*ch);let both=0,total=0;for(let x=0;x<w;x++){const t=y>0?mask[(y-1)*w+x]:0,b=y<h?mask[Math.min(h-1,y)*w+x]:0;total++;if(t&&b)both++}penalty+=both/Math.max(1,total)*2;checks++}}return checks?penalty/checks:0}
export function smartDetect(img){const{mask,width,height}=makeMask(img),compMask=closeMask(mask,width,height,1,2),comps=extractComponents(compMask,width,height,18),major=pickMajorComponents(comps),hint=stripHint(mask,width,height,comps),sepHint=separatorGridHint(mask,width,height,major),majorCount=Math.max(1,major.length,sepHint?Math.round(sepHint.cols*sepHint.rows*.75):1),sx=strongSeparators(mask,width,height,'x'),sy=strongSeparators(mask,width,height,'y'),guess=estimateComponentGrid(comps,width,height),xClusterCount=cluster1D(major.map(c=>c.cx),Math.max(10,width*.08)).length,yClusterCount=cluster1D(major.map(c=>c.cy),Math.max(10,height*.12)).length;let best={cols:1,rows:1,score:Infinity,used:1};for(let cols=1;cols<=12;cols++)for(let rows=1;rows<=12;rows++){const cw=width/cols,ch=height/rows,cells=cols*rows,used=usedFrames(mask,width,height,cols,rows),usage=used/cells;let score=0;score+=axisScore(mask,width,height,cols,'x',sx);score+=axisScore(mask,width,height,rows,'y',sy);score+=gridScore(mask,width,height,cols,rows);score+=centerAlignmentPenalty(major,width,height,cols,rows)*2;score+=multiPeakPenalty(mask,width,height,cols,rows)*2.1;score+=sizePreferencePenalty(cw,ch);score+=Math.abs(cols-guess.cols)*.35+Math.abs(rows-guess.rows)*.35;let over=overSegPenalty(cols,rows,majorCount,guess.cols,guess.rows);if(sepHint&&(cols===sepHint.cols||rows===sepHint.rows))over*=.18;score+=over;score+=tinyOccupancyPenalty(mask,width,height,cols,rows);score+=boundaryCutPenalty(mask,width,height,cols,rows);if(hint){score+=Math.abs(cols-hint.cols)*1.25+Math.abs(rows-hint.rows)*1.25;if(cols===hint.cols&&rows===hint.rows)score-=3.5}if(sepHint){score+=Math.abs(cols-sepHint.cols)*2.8+Math.abs(rows-sepHint.rows)*2.8;if(cols===sepHint.cols&&rows===sepHint.rows)score-=5+sepHint.strength*2.4}if(rows===1&&yClusterCount>=2)score+=(yClusterCount-1)*3.2;if(cols===1&&xClusterCount>=2)score+=(xClusterCount-1)*3.2;if(usage<.18)score+=2;if(cells===1&&major.length>1)score+=2.5;if(sepHint&&cells===1&&sepHint.cols*sepHint.rows>=4)score+=12;if(score<best.score)best={cols,rows,score,used}}return best}
